/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'id' : IDL.Nat,
  'appearance' : IDL.Text,
  'name' : IDL.Text,
  'riddle' : IDL.Text,
  'answer' : IDL.Text,
  'story' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
  'getUnlockedCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'unlockCharacter' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'appearance' : IDL.Text,
    'name' : IDL.Text,
    'riddle' : IDL.Text,
    'answer' : IDL.Text,
    'story' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
    'getUnlockedCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'unlockCharacter' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };